<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FarmerOps.Application\FarmerOps.Application.csproj" />
    <ProjectReference Include="..\FarmerOps.Infrastructure\FarmerOps.Infrastructure.csproj" />
    <ProjectReference Include="..\FarmerOps.Domain\FarmerOps.Domain.csproj" />
  </ItemGroup>

</Project>
